workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        NODE_VERSION: "16"  # Optional: specify Node.js version
        BUNDLE_ID: "io.codemagic.sample.reactnative"
        XCODE_WORKSPACE: "CodemagicSample.xcworkspace"  # Name of your Xcode workspace
        XCODE_SCHEME: "CodemagicSample"  # Name of your Xcode scheme
    scripts:
      - name: Install dependencies
        script: |
          npm install  # Or yarn install if you use yarn
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
